mail:
  username: projectreldi@gmail.com
  password: reldirulz2017

url:
  prefix: "/services"


csmtiser:
  working_dir: /home/mperice/Projects/csmtiser
  encoding: utf8
  tokenseparator: £
  tokenise: False
  truecase: False
  truecase_dataset: datasets/sentence_level/tweet_sl.all
  truecase_model: None
  lowercase: False
  align: False
  train_orig: datasets/sentence_level/tweet_sl.orig
  train_norm: datasets/sentence_level/tweet_sl.norm
  dev_perc: 0.1
  dev_orig: None
  dev_norm: None
  lm_order: 10
  lms:
    - datasets/sentence_level/tweet_sl
  moses_scripts: /home/mperice/Projects/mosesdecoder/scripts/
  kenlm: /home/mperice/Projects/mosesdecoder/bin/
  moses: /home/mperice/Projects/mosesdecoder/moses-cmd/bin/gcc-4.9.2/release/link-static/threading-multi
  mgiza: /home/mperice/Projects/mgiza/mgizapp/bin/
  num_cores: 2